Repository fga-eps-mds/2024.1-UnB-TV-Frontend, pull requests merged in 2024-09, with the labels that each got.

#21 US15 - Eu, como usuário, quero ter telas personalizadas a partir da tela de "Sua UnBTV", para visualizar conteúdos relacionados a mim.
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/components/background/background.component.html
  src/app/components/background/background.component.ts
  src/app/pages/catalog/catalog.component.html
  src/app/pages/catalog/catalog.component.spec.ts
  src/app/pages/catalog/catalog.component.ts
  src/app/pages/favorite-videos/favorite-videos.component.css
  src/app/pages/favorite-videos/favorite-videos.component.html
  src/app/pages/favorite-videos/favorite-videos.component.spec.ts
  src/app/pages/favorite-videos/favorite-videos.component.ts
  src/app/pages/recommendation-videos/recommendation-videos.component.css
  src/app/pages/recommendation-videos/recommendation-videos.component.html
  src/app/pages/recommendation-videos/recommendation-videos.component.spec.ts
  src/app/pages/recommendation-videos/recommendation-videos.component.ts
  src/app/pages/record/record.component.html
  src/app/pages/record/record.component.ts
  src/app/pages/video-viewer/video-viewer.component.spec.ts
  src/app/pages/watchlater-videos/watchlater-videos.component.css
  src/app/pages/watchlater-videos/watchlater-videos.component.html
  src/app/pages/watchlater-videos/watchlater-videos.component.spec.ts
  src/app/pages/watchlater-videos/watchlater-videos.component.ts
  src/app/pages/your-unbtv/your-unbtv.component.css
  src/app/pages/your-unbtv/your-unbtv.component.html
  src/app/pages/your-unbtv/your-unbtv.component.spec.ts
  src/app/pages/your-unbtv/your-unbtv.component.ts
  src/app/services/video.service.ts
  test-reports/TESTS.xml
Labels: MINOR RELEASE

#20 US05 - Eu, como administrador, quero alterar os cargos de outros usuários por meio da tela de administrador
  src/app/app-routing.module.ts
  src/app/app.module.ts
  src/app/pages/controle-super-admin/controle-super-admin.component.css
  src/app/pages/controle-super-admin/controle-super-admin.component.html
  src/app/pages/controle-super-admin/controle-super-admin.component.spec.ts
  src/app/pages/controle-super-admin/controle-super-admin.component.ts
  src/app/pages/stream-view/stream-view.component.spec.ts
  src/app/pages/update-role/update-role.component.html
  src/app/pages/update-role/update-role.component.spec.ts
  src/app/pages/update-role/update-role.component.ts
  src/app/services/user.service.ts
  test-reports/TESTS.xml
Labels: MAJOR RELEASE

#22 23 excluir historico
  src/app/pages/record/record.component.css
  src/app/pages/record/record.component.html
  src/app/pages/record/record.component.spec.ts
  src/app/pages/record/record.component.ts
  src/app/services/video.service.spec.ts
  src/app/services/video.service.ts
  src/assets/icons/32px-Cross_red_circle.svg.png
Labels: MINOR RELEASE

#23 Aumento da cobertura de testes e resolução de issues do SonarCloud.
  src/app/app-routing.module.ts
  src/app/components/background/background.component.ts
  src/app/pages/controle-super-admin/controle-super-admin.component.css
  src/app/pages/controle-super-admin/controle-super-admin.component.html
  src/app/pages/edit-user/edit-user.component.ts
  src/app/pages/update-role/update-role.component.html
Labels: FIX RELEASE
